### ISSUE TITLE
Trouble getting from last two weaks cant able to solve the problem

### ISSUE THREAD

**Issue by madilraza** [wangchi/github-packages-demo#1]
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by taroalan** [comment]
May be a file permission issue，try like this:
`su npm publish` or `sudo npm publish`
